### ISSUE TITLE
Does the shader work with HtoA 2.x? 

### ISSUE THREAD

**Issue by japasa** [Psyop/jf-nested-dielectric#10]
Hi, 

I tried to install the shader “JF Nested Dielectric” in houdini on both platforms WIN/MAC. 

I copied jf_nested_dielectric.dylib and jf_nested_dielectric.mtd to the plugin folder of HtoA. I changed the parameter of the *.mtd-file: 

********************************************************************************************************
[node jf_nested_dielectric]

desc STRING „JF Nested Dielectric By Jonah Friedman v1.0.5, Copyright (c) 2014, Psyop Media Company, LLC and Jonah Friedman“

houdini.icon STRING ”SHOP_surface“
houdini.category STRING ”alShaders"
houdini.help_url STRING "https://github.com/Psyop/jf-nested-dielectric/blob/master/documentation/jf_nested_dielectric_manual.pdf"

[attr mediumpriority]
		
		min FLOAT 0.0
		max FLOAT 1.0
		linkable BOOL TRUE

[attr mediumtransmittance scale]
********************************************************************************************************

the shader works with arnold 4.2 only. it seems that jf_nested_dielectric.dylib probably doesn't work with Arnold 5 for Houdini. 

I hope to look foward hearing from anybody. thanks! 

Best regards, 
Patric

**Comment by jonahfriedman** [comment]
Nope, it does not work in Arnold 5 yet, but I'm hoping for contributions that will fix that. It's not a small project though.
