### ISSUE TITLE
Not loading on OSX C4DtoA

### ISSUE THREAD

**Issue by bonsak** [Psyop/jf-nested-dielectric#4]
Trying to use "jf-nested-dielectric" with C4DotA and i get this error:

```
WARNING| unable to load dynamic library: dlopen(/Applications/Maxon/CINEMA 4D R16/plugins/C4DtoA/shaders/jf_nested_dielectric.so, 5): no suitable image found.  Did find:/Applications/Maxon/CINEMA 4D R16/plugins/C4DtoA/shaders/jf_nested_dielectric.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

"jf_nested_dielectric.so" is in the "/Applications/Maxon/CINEMA 4D R16/plugins/C4DtoA/shaders/" folder

Not sure if the 4.1.3.3 binaries are supposed to work with Arnold v4.2.6.2

**Comment by jonahfriedman** [comment]
Could you double check that you didn't download the Linux binaries by accident? It should be binary compatible with 4.2.x.

**Comment by bonsak** [comment]
I'm using this one: 
'
jf-nested-dielectric-master/binaries/v1.0.2/osx/arnold_4.1.3.3/jf_nested_dielectric.so
'

**Comment by jonahfriedman** [comment]
I don't have a OS X setup so I haven't tested that one. It's possible that binary is actually a linux binary by mistake. 

Could you try this one: https://github.com/Psyop/jf-nested-dielectric/tree/master/binaries/v1.0.0/osx/arnold_4.1.3.3?

**Comment by bonsak** [comment]
It gives the same error.

**Comment by jonahfriedman** [comment]
Sorry I couldn't help you, closing this to clean up old tickets.
