### ISSUE TITLE
How to compile in Linux?

### ISSUE THREAD

**Issue by shdwdln** [Psyop/jf-nested-dielectric#5]
I am trying to compile in linux under centos 7 with Arnold SDK (4.2.13.0).

I added a couple lines to the FindArnold.cmake:

```
set(ARNOLD_LIBRARY "/home/shdwdln/solidangle/Arnold-4.2.13.0-linux_SDK/include/bin/libai.so")
set(ARNOLD_INCLUDE_DIR "/home/shdwdln/solidangle/Arnold-4.2.13.0-linux_SDK/include")
set(ARNOLD_HOME "/home/shdwdln/solidangle/Arnold-4.2.13.0-linux_SDK")
```

Then I run:
`$ cmake .. -DCMAKE_PREFIX_PATH=/home/shdwdln/solidangle`

and it says:

```
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_PREFIX_PATH

-- Build files have been written to: /home/shdwdln/Downloads/jf-nested-dielectric/build
```

So I continue and run:

`$ make`

and the output is:

```
make[2]: *** No rule to make target `/home/shdwdln/solidangle/Arnold-4.2.13.0-linux_SDK/include/bin/libai.so', needed by `source/jf_nested_dielectric.so'.  Stop.
make[1]: *** [source/CMakeFiles/jf_nested_dielectric.dir/all] Error 2
make: *** [all] Error 2
```

What am I missing here?

**Comment by matsbtegner** [comment]
On 2016-03-13 18:54, shdwdln wrote:
> I am trying to compile in linux under centos 7 with Arnold SDK (4.2.13.0).
> 
> I added a couple lines to the FindArnold.cmake:
> 
> ```
> set(ARNOLD_LIBRARY "/home/shdwdln/solidangle/Arnold-4.2.13.0-linux_SDK/include/bin/libai.so")

Change ARNOLD_LIBRARY to: /Arnold-4.2.13.0-linux_SDK/bin/libai.so

Mats

**Comment by jonahf** [comment]
Thanks guys, for working this out. I don't have a linux setup myself, those cmake files were contributed by Chad. If one of you makes this into a pull request I'll glady accept it.

**Comment by matsbtegner** [comment]
I've just rebuilt the plugin under Slackware Linux and I didn't modify the FindArnold.cmake. CMake did find the Arnold version. I have these relevant environment variables in .bash_profile e.g:
```
export ARNOLD_PATH=~/solidangle/releases/Arnold-4.2.12.3-linux
export PATH=$ARNOLD_PATH/bin:$PATH
```

**Comment by jonahfriedman** [comment]
Thanks, closing this. I'm going to open another issue to overhaul the build system, perhaps just copy the one from AlShaders since everyone is comfortable with that.
