### ISSUE TITLE
Doesn't work maya 2017 update 3

### ISSUE THREAD

**Issue by nektart** [Psyop/jf-nested-dielectric#8]
I don't know why, but it doesn't work on the update 3.

**Comment by ddankhazi** [comment]
It's working for me. 
It's not working how? You can't find the shader or Arnold not rendering the surface or you have priority problems.
A bit more information would be awesome.
Cheers, D

p.s. Did you reinstall the files after the Maya update?

**Comment by jonahfriedman** [comment]
Maya works fine, could this be a Arnold 5 problem? In any case, closing this, but feel free to reopen if you have more details.
