### ISSUE TITLE
Arnold 5.0.0.0

### ISSUE THREAD

**Issue by ddankhazi** [Psyop/jf-nested-dielectric#9]
Hi Jonah,
There will be a compatible version with the new Arnold?
Cheers, Denes

**Comment by jonahfriedman** [comment]
At some point, yeah. I also have a beta version for Arnold 4 that's been in beta for.. 2 years now. Heh. 

I could do a minimal port for compatibility, or I could do something more comprehensive that actually makes use of the closures and other new features. I hope to do the latter, but I'm not sure when I'll have time.

**Comment by ddankhazi** [comment]
Thank you for your answer.
By the way your shader is absolutely awesome.
Cheers, Denes
